<script lang="ts">
    import { Newspaper, ChevronLeft, ChevronRight, RefreshCcw } from 'lucide-svelte';
    import Button from '../Button.svelte';
    import Dialog from '../Dialog.svelte';
    import type { ImoLogEntry } from '../../private-types.js';
    import { imoLogs } from '../state/imoLogs.svelte.js';

    type Props = {
        show: boolean;
    };

    let { show: showLog = $bindable(false) }: Props = $props();

    let currentLogSetIndex = $state(0);
    const logSet = $derived(imoLogs.current[currentLogSetIndex] || []);
</script>

{#snippet logLine(entry: ImoLogEntry, firstTimestamp: number, _index: number)}
    {@const elapsed = entry.timestamp - firstTimestamp}
    <p>
        <span class="elapsed">+{elapsed}</span>
        <span class="time-stamp">{new Date(entry.timestamp).toLocaleTimeString()}</span>
        <span class={['log-level', entry.level.toLowerCase()]}>{entry.level}</span>:
        <span class="message">{entry.message}</span>
    </p>
{/snippet}

<Dialog bind:show={showLog}>
    {#snippet title()}
        <h2>
            <Newspaper /> IMO Logs
        </h2>
    {/snippet}
    <p>Below are the logs generated by <code>@collagejs/imo</code> during this session.</p>
    <div class="log-sets">
        <Button
            variant="primary"
            class="cjs-gap-1"
            disabled={currentLogSetIndex === 0}
            onclick={() => {
                if (currentLogSetIndex > 0) {
                    currentLogSetIndex -= 1;
                }
            }}
        >
            <ChevronLeft size={16} />
            &nbsp;Previous
        </Button>
        <Button
            variant="primary"
            class="cjs-gap-1"
            disabled={currentLogSetIndex >= imoLogs.current.length - 1}
            onclick={() => {
                if (currentLogSetIndex < imoLogs.current.length - 1) {
                    currentLogSetIndex += 1;
                }
            }}
        >
            Next&nbsp;
            <ChevronRight size={16} />
        </Button>
        <span>
            Log Set {currentLogSetIndex + 1} of {imoLogs.current.length}
        </span>
    </div>
    {#if imoLogs.current.length}
        <p class="log-summary">
            Excecution Start: <span>
                {new Date(logSet[0].timestamp).toLocaleString()}
            </span>
            ({logSet.length} log entr{logSet.length === 1 ? 'y' : 'ies'})
        </p>
    {/if}
    <div class="log-entries">
        {#if imoLogs.current.length === 0}
            <p><em>No logs recorded.</em></p>
        {:else}
            {#each logSet as entry, index}
                {@render logLine(entry, logSet[0].timestamp, index)}
            {/each}
        {/if}
    </div>
</Dialog>

<style>
    .log-summary {
        font-style: italic;
        font-weight: bolder;
        margin: 0.5rem 0 0 0;
        text-align: right;
    }
    .log-entries {
        padding: 1rem;
        border: 0.15rem dashed rgba(0, 0, 0, 0.2);
        max-height: 20rem;
        overflow: auto;
        font-family: monospace;
        margin: 1rem 0;

        & > p {
            margin: 0.25rem 0;

            & > .elapsed {
                color: var(--cjs-brand-green-end);
                text-align: right;
                display: inline-block;
                width: 6ch;

                :global(.cjs-theme-dark) & {
                    color: var(--cjs-brand-green-start);
                }
            }

            & > .time-stamp {
                margin-right: 0.5rem;
            }

            & > .log-level {
                font-weight: bold;

                &.info {
                    color: var(--cjs-brand-cyan-end);
                }

                &.warning {
                    color: var(--cjs-brand-orange-end);
                }

                &.error {
                    color: var(--cjs-error);
                }
            }
        }
    }
    .log-sets {
        display: flex;
        align-items: center;
        gap: 0.5rem;
        margin-top: 0.5rem;
    }
</style>
